config:
  # ===========================================================================
  # Laravel Application Configuration
  # ===========================================================================
  laravel:environment: staging
  laravel:debug: "true"
  laravel:appName: "Laravel Headless Starter - Staging"
  laravel:appUrl: "https://staging-api.example.com"
  laravel:appKey:
    secure: AAABAQ... # Set with: pulumi config set --secret laravel:appKey "base64:..."
  laravel:namespace: "laravel-staging"

  # Scaling configuration
  laravel:webReplicas: "2"
  laravel:webMinReplicas: "2"
  laravel:webMaxReplicas: "10"
  laravel:workerReplicas: "2"
  laravel:workerMinReplicas: "1"
  laravel:workerMaxReplicas: "20"
  laravel:reverbReplicas: "1"
  laravel:reverbMinReplicas: "1"
  laravel:reverbMaxReplicas: "3"

  # Resource limits
  laravel:webMemoryLimit: "1Gi"
  laravel:webMemoryRequest: "512Mi"
  laravel:webCpuLimit: "1"
  laravel:webCpuRequest: "0.5"
  laravel:workerMemoryLimit: "512Mi"
  laravel:workerMemoryRequest: "256Mi"
  laravel:workerCpuLimit: "0.5"
  laravel:workerCpuRequest: "0.25"

  # ===========================================================================
  # Unified Database Configuration
  # ===========================================================================
  database:engine: postgresql
  database:version: "16"
  database:extensions:
    - uuid-ossp
    - pg_trgm
  database:enablePostGIS: false
  database:enableTimescaleDB: false

  # ===========================================================================
  # PostgreSQL Configuration
  # ===========================================================================
  postgres:enabled: "false" # Use managed RDS in staging
  postgres:host: "staging-db.xxxxx.us-east-1.rds.amazonaws.com"
  postgres:port: "5432"
  postgres:database: "laravel_staging"
  postgres:username: "laravel_staging"
  postgres:password:
    secure: AAABAQ...
  postgres:replicas: "1"
  postgres:storageSize: "50Gi"

  # ===========================================================================
  # Unified Cache Configuration
  # ===========================================================================
  cache:engine: redis
  cache:version: "7.4"
  cache:persistence: true
  cache:evictionPolicy: allkeys-lru

  # ===========================================================================
  # Redis Configuration
  # ===========================================================================
  redis:enabled: "false" # Use managed ElastiCache in staging
  redis:host: "staging-redis.xxxxx.cache.amazonaws.com"
  redis:port: "6379"
  redis:version: "7.4"
  redis:password:
    secure: AAABAQ...
  redis:replicas: "1"
  redis:tls: "true"

  # ===========================================================================
  # Unified Queue Configuration
  # ===========================================================================
  queue:engine: rabbitmq
  queue:version: "3.13"
  queue:managementUI: true
  queue:kraftMode: false

  # ===========================================================================
  # Kafka Configuration
  # ===========================================================================
  kafka:enabled: "false" # Use managed MSK in staging
  kafka:brokers: "b-1.staging-kafka.xxxxx.kafka.us-east-1.amazonaws.com:9092"
  kafka:version: "3.8"
  kafka:replicas: "1"
  kafka:storageSize: "50Gi"

  # ===========================================================================
  # RabbitMQ Configuration
  # ===========================================================================
  rabbitmq:enabled: "true" # In-cluster for staging
  rabbitmq:host: "rabbitmq"
  rabbitmq:port: "5672"
  rabbitmq:version: "3.13-management"
  rabbitmq:managementPort: "15672"
  rabbitmq:username: "rabbitmq_staging"
  rabbitmq:password:
    secure: AAABAQ...
  rabbitmq:replicas: "1"
  rabbitmq:tls: "false"

  # ===========================================================================
  # Storage Configuration (MinIO)
  # ===========================================================================
  minio:enabled: "false" # Use S3 in staging
  s3:bucket: "laravel-staging-assets"
  s3:region: "us-east-1"
  s3:accessKey:
    secure: AAABAQ...
  s3:secretKey:
    secure: AAABAQ...

  # ===========================================================================
  # Search Configuration (Meilisearch)
  # ===========================================================================
  meilisearch:enabled: "true"
  meilisearch:host: "http://meilisearch:7700"
  meilisearch:masterKey:
    secure: AAABAQ...
  meilisearch:replicas: "1"

  # ===========================================================================
  # Mail Catcher Configuration
  # ===========================================================================
  mailCatcher:tool: none
  mailpit:enabled: "false" # Use real email service in staging

  # ===========================================================================
  # PHP Runtime Configuration
  # ===========================================================================
  phpRuntime:type: octane
  phpRuntime:version: "8.3"
  phpRuntime:octaneServer: frankenphp
  phpRuntime:opcacheEnabled: true
  phpRuntime:opcacheMemory: 256

  # ===========================================================================
  # Ingress Configuration
  # ===========================================================================
  ingress:enabled: "true"
  ingress:className: "nginx"
  ingress:host: "staging-api.example.com"
  ingress:tls: "true"
  ingress:tlsSecretName: "staging-tls-cert"
  ingress:annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rate-limit: "100"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"

  # ===========================================================================
  # Observability Configuration
  # ===========================================================================
  observability:prometheus: "true"
  observability:grafana: "true"
  observability:loki: "true"
  observability:tempo: "false"
  observability:alertmanager: "true"

  # ===========================================================================
  # Feature Flags
  # ===========================================================================
  features:hpa: "true"
  features:pdb: "true"
  features:networkPolicies: "true"
  features:podSecurityPolicies: "true"
  features:resourceQuotas: "true"
